# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ffae629a73df57315494e38008dd0cd"
name = "aj-test"
handle = "aj-test-1"
application_url = "https://hosting-seek-pink-ts.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-16d83037.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hosting-seek-pink-ts.trycloudflare.com/auth/callback",
  "https://hosting-seek-pink-ts.trycloudflare.com/auth/shopify/callback",
  "https://hosting-seek-pink-ts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
